[package]
name = "pallet-encointer-ceremonies"
version = "0.8.1"
authors = ["encointer.org <alain@encointer.org>"]
edition = "2018"

[dependencies]
log = { version = "0.4.14", default-features = false }
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false }

# local deps
encointer-primitives = { path = "../primitives", default-features = false }
encointer-balances = { package = "pallet-encointer-balances", path = "../balances", default-features = false }
encointer-ceremonies-assignment = { path = "assignment", default-features = false }
encointer-communities = { package = "pallet-encointer-communities", path = "../communities", default-features = false }
encointer-scheduler = { package = "pallet-encointer-scheduler", path = "../scheduler", default-features = false }

# substrate deps
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
pallet-timestamp = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-runtime = {  git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-std = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }

[dev-dependencies]
approx = "0.5.1"
itertools = "0.10.3"
rstest = "0.12.0"
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17" }
sp-io = {  git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17" }
test-utils = { path = "../test-utils" }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-std/std",
	"pallet-timestamp/std",
	"encointer-balances/std",
	"encointer-ceremonies-assignment/std",
	"encointer-communities/std",
	"encointer-primitives/std",
	"encointer-scheduler/std",
]
