[package]
name = "encointer-ceremonies-assignment"
version = "0.1.0"
edition = "2021"

[dependencies]

# local deps
encointer-primitives = { path = "../../primitives", default-features = false }

# substrate deps
sp-runtime = {  git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-std = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }

[dev-dependencies]
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17" }

[features]
default = ["std"]
std = [
    "encointer-primitives/std",
    "sp-std/std",
    "sp-runtime/std",
]
