[package]
name = "pallet-encointer-communities"
version = "0.8.1"
authors = ["encointer.org <alain@encointer.org>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0.0", default-features = false }

# local deps
encointer-primitives = { path = "../primitives", default-features = false }
encointer-balances = { package = "pallet-encointer-balances", path = "../balances", default-features = false }
encointer-scheduler = { package = "pallet-encointer-scheduler", path = "../scheduler", default-features = false }

# substrate deps
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, optional = true, branch = "polkadot-v0.9.17" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-io = {  git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-std = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }
sp-runtime = {  git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.17" }

[dev-dependencies]
approx = "0.5.1"
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17" }
test-utils = {path ="../test-utils" }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",

	# local deps
	"encointer-primitives/std",
	"encointer-balances/std",
	"encointer-scheduler/std",

	# substrate deps
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-std/std",
	"sp-runtime/std",
]
runtime-benchmarks = ["frame-benchmarking"]

